//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DictionaryAdvanced.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DictionaryAdvanced.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Direction.
        /// </summary>
        internal static string CharDirCaption {
            get {
                return ResourceManager.GetString("CharDirCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Character Direction.
        /// </summary>
        internal static string CharDirTooltip {
            get {
                return ResourceManager.GetString("CharDirTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Format.
        /// </summary>
        internal static string CharFormatCaption {
            get {
                return ResourceManager.GetString("CharFormatCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Character Format.
        /// </summary>
        internal static string CharFormatTooltip {
            get {
                return ResourceManager.GetString("CharFormatTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary Array Output.
        /// </summary>
        internal static string DictionaryArrayOutputCaption {
            get {
                return ResourceManager.GetString("DictionaryArrayOutputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Dictionary as String Array.
        /// </summary>
        internal static string DictionaryArrayOutputTooltip {
            get {
                return ResourceManager.GetString("DictionaryArrayOutputTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary.
        /// </summary>
        internal static string DictionaryLangCaption {
            get {
                return ResourceManager.GetString("DictionaryLangCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Keyword Dictionary.
        /// </summary>
        internal static string DictionaryLangTooltip {
            get {
                return ResourceManager.GetString("DictionaryLangTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary Length Output.
        /// </summary>
        internal static string DictionaryLengthOutputCaption {
            get {
                return ResourceManager.GetString("DictionaryLengthOutputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Dictionary Length.
        /// </summary>
        internal static string DictionaryLengthOutputTooltip {
            get {
                return ResourceManager.GetString("DictionaryLengthOutputTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary String Output.
        /// </summary>
        internal static string DictionaryStringOutputCaption {
            get {
                return ResourceManager.GetString("DictionaryStringOutputCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Dictionary as a String.
        /// </summary>
        internal static string DictionaryStringOutputTooltip {
            get {
                return ResourceManager.GetString("DictionaryStringOutputTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Output Type - String or Loop Words.
        /// </summary>
        internal static string DictionaryStringOutputTypeTooltip {
            get {
                return ResourceManager.GetString("DictionaryStringOutputTypeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary Advanced.
        /// </summary>
        internal static string PluginCaption {
            get {
                return ResourceManager.GetString("PluginCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Dictionary for Advanced Cryptography &amp; Cryptanalysis.
        /// </summary>
        internal static string PluginTooltip {
            get {
                return ResourceManager.GetString("PluginTooltip", resourceCulture);
            }
        }
    }
}
